// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TaskcarCompletedTask struct {
	TaskID        int64
	CreatedAt     pgtype.Timestamptz
	Queue         string
	TaskCreatedAt pgtype.Timestamptz
	InData        []byte
	OutData       []byte
	Log           string
	Attempts      int32
	NodeID        int64
}

type TaskcarFailedTask struct {
	ID            int64
	TaskID        int64
	CreatedAt     pgtype.Timestamptz
	Queue         string
	TaskCreatedAt pgtype.Timestamptz
	NodeID        int64
	InData        []byte
	Log           string
	Attempts      int32
}

type TaskcarNode struct {
	NodeID      int64
	CreatedAt   pgtype.Timestamptz
	Hostname    string
	IpAddress   string
	HeartbeatAt pgtype.Timestamptz
	Up          bool
}

type TaskcarQueue struct {
	Queue       string
	CreatedAt   pgtype.Timestamptz
	MaxAttempts int32
	BackoffPath []string
	BackoffInt  pgtype.Interval
}

type TaskcarSecret struct {
	SecretID  int64
	CreatedAt pgtype.Timestamptz
	Name      string
	Value     string
}

type TaskcarSystemconfig struct {
	ConfigID  int64
	CreatedAt pgtype.Timestamptz
	Name      string
	Value     string
}

type TaskcarTask struct {
	TaskID    int64
	CreatedAt pgtype.Timestamptz
	Queue     string
	InData    []byte
	Attempts  int32
	LockedBy  *int64
}

type TaskcarTaskBackedoff struct {
	TaskID int64
}

type TaskcarTaskBackoff struct {
	ID          int64
	Queue       string
	BackoffKey  []byte
	Until       pgtype.Timestamptz
	BackoffPath []string
}
